$ANSIBLE_VAULT;1.1;AES256
64656263323065356666333731383064333033666266353162666365373565343733363730313033
6264643262343630613732373130386663376564623730370a316631653732343532346131623066
38393637623835646364616665303339383065626238613962643066646534646237653462613463
3931376537373361300a353634323838663265363831323434303430373130396139643639333835
36313561326232343031666632393563626330363633326636313834313938616236366662646632
65313237366664656265346136353330616535393763666334323566326264623664316237323163
62666165363863666136363363623335393237663132623065366266336439366536396234646638
63383732323232333831383661373437323632323733613539663435313939343735346334386232
31336666336163393161393331623662633139343930633834633337623332306330653934323332
63666132393536366261613034303631343831363034326265326532613435346131626436623532
35616465303963366135396634333639313764383134393038336562623338646265303439333162
38376664323234643134656665613130373862376430313139386665383636646431343434373834
32626233393362666437623632346635323664363833636531336134396566633434
